import * as React from 'react';
import {
  Home,
  Goal,
  Check,
  Checkbox,
  CheckboxOn,
  Fire,
  BookOpen,
  Notebook,
  Notes,
  Chart,
  ChartBarBig,
  Star,
  Calendar,
  Clock,
  Cpu,
  Robot,
  Trophy,
  Crown,
  Zap,
  Sword,
  Shield,
  Heart,
  Sparkles,
  Target,
  Compass,
  Map,
  Handbag,
  Settings2,
  User,
  Users,
  Gear,
  Bell,
  Cloud,
  Wifi,
  Plug,
  Power,
  Logout,
  Login,
  Plus,
  PlusBox,
  Trash,
  Delete,
  Pencil,
  Search,
  Filter,
  SortVertical,
  Copy,
  Undo,
  Redo,
  Refresh,
  Reload,
  Download,
  Upload,
  ExternalLink,
  Link,
  Close,
  Cross,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  MoreVertical,
  MoreHorizontal,
  Menu,
  DragAndDrop,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Flag,
  Grid3x3,
  ListBox,
  Image,
  File,
  FileText,
  Mail,
  Send,
  Message,
  Terminal,
  Code,
  Bug,
  InfoBox,
  CircleInfo,
  WarningDiamond,
  SquareAlert,
  Sun,
  Moon,
  Volume,
  Mic,
  Camera,
  Video,
  Phone,
  Smartphone,
  Computer,
  Database,
  Server,
  Coins,
  Dollar,
  Gift,
  PartyPopper,
  Smile,
  Meh,
  Frown,
  Alien,
  Gamepad,
  Joystick,
  Castle,
  Skull,
  Bomb,
  Wand,
  MagicEdit,
  Lightbulb,
  QuoteTextInline,
  Section,
  Sticker,
  Bookmark,
  Archive,
  Inbox,
  Package,
  Box,
  ShoppingCart,
  Store,
  Briefcase,
  Suitcase,
  Building,
  Tree,
  Leaf,
  Coffee,
  Mug,
  Tea,
  Dog,
  Fish,
  Cake,
  PenSquare,
  StickyNote,
  StickyNoteText,
  Hourglass,
  AlarmClock,
  Watch,
  CalendarText,
  CalendarWeeks,
  TrendingUp,
  SpeedFast,
  SpeedMedium,
  SpeedSlow,
  Battery,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  CellularSignal0,
  CellularSignal1,
  CellularSignal2,
  CellularSignal3,
  Globe,
  MapPin,
  RoadSign,
  Directions,
  Tools,
  ToolCase,
  Brush,
  QrCode,
  Barcode,
  GalleryThumbnails,
  ColorsSwatch,
  AiScan,
} from 'pixelarticons/react';

/**
 * PixelIcon — the SINGLE application entry point for Pixelarticons.
 *
 * Per Refinement Master Pack (ASSETS.md / DESIGN.md §5) Pixelarticons is the
 * PRIMARY personality/navigation icon system. This abstraction:
 *   - maps a curated semantic `name` → the installed React component
 *   - co-locates the icon policy in one file (no scattered pixelarticons imports)
 *   - forwards standard SVG props (size, color, className, title/aria)
 *   - keeps Lucide as the UTILITY layer (close, chevron, drag, etc. live there)
 *
 * To add a new icon: extend `PIXEL_ICONS` with the imported component. The
 * mapping is intentionally explicit (not a dynamic `icons[name]`) so tree-
 * shaking works and missing icons fail loudly at build time, not runtime.
 */
export type PixelIconName = keyof typeof PIXEL_ICONS;

const PIXEL_ICONS = {
  home: Home,
  goal: Goal,
  check: Check,
  checkbox: Checkbox,
  checkboxOn: CheckboxOn,
  fire: Fire,
  book: BookOpen,
  notebook: Notebook,
  notes: Notes,
  chart: Chart,
  chartBar: ChartBarBig,
  star: Star,
  calendar: Calendar,
  clock: Clock,
  cpu: Cpu,
  robot: Robot,
  trophy: Trophy,
  crown: Crown,
  award: Trophy,
  zap: Zap,
  sword: Sword,
  shield: Shield,
  heart: Heart,
  sparkles: Sparkles,
  target: Target,
  compass: Compass,
  map: Map,
  bag: Handbag,
  settings: Settings2,
  user: User,
  users: Users,
  gear: Gear,
  bell: Bell,
  cloud: Cloud,
  wifi: Wifi,
  plug: Plug,
  power: Power,
  logout: Logout,
  login: Login,
  plus: Plus,
  plusBox: PlusBox,
  trash: Trash,
  delete: Delete,
  edit: Pencil,
  pencil: Pencil,
  search: Search,
  filter: Filter,
  sort: SortVertical,
  copy: Copy,
  undo: Undo,
  redo: Redo,
  refresh: Refresh,
  reload: Reload,
  download: Download,
  upload: Upload,
  externalLink: ExternalLink,
  link: Link,
  close: Close,
  cross: Cross,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  moreVertical: MoreVertical,
  moreHorizontal: MoreHorizontal,
  menu: Menu,
  drag: DragAndDrop,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  flag: Flag,
  grid: Grid3x3,
  list: ListBox,
  image: Image,
  file: File,
  fileText: FileText,
  mail: Mail,
  send: Send,
  message: Message,
  terminal: Terminal,
  code: Code,
  bug: Bug,
  info: InfoBox,
  circleInfo: CircleInfo,
  warning: WarningDiamond,
  squareAlert: SquareAlert,
  sun: Sun,
  moon: Moon,
  volume: Volume,
  mic: Mic,
  camera: Camera,
  video: Video,
  phone: Phone,
  smartphone: Smartphone,
  computer: Computer,
  database: Database,
  server: Server,
  coins: Coins,
  dollar: Dollar,
  gift: Gift,
  party: PartyPopper,
  smile: Smile,
  meh: Meh,
  frown: Frown,
  alien: Alien,
  gamepad: Gamepad,
  joystick: Joystick,
  castle: Castle,
  skull: Skull,
  bomb: Bomb,
  wand: Wand,
  magic: MagicEdit,
  bulb: Lightbulb,
  quote: QuoteTextInline,
  section: Section,
  sticker: Sticker,
  bookmark: Bookmark,
  archive: Archive,
  inbox: Inbox,
  package: Package,
  box: Box,
  cart: ShoppingCart,
  store: Store,
  briefcase: Briefcase,
  suitcase: Suitcase,
  building: Building,
  tree: Tree,
  leaf: Leaf,
  coffee: Coffee,
  mug: Mug,
  tea: Tea,
  dog: Dog,
  fish: Fish,
  cake: Cake,
  pen: PenSquare,
  sticky: StickyNote,
  stickyText: StickyNoteText,
  hourglass: Hourglass,
  alarm: AlarmClock,
  watch: Watch,
  calendarText: CalendarText,
  calendarWeeks: CalendarWeeks,
  trending: TrendingUp,
  speedFast: SpeedFast,
  speedMedium: SpeedMedium,
  speedSlow: SpeedSlow,
  battery: Battery,
  batteryFull: BatteryFull,
  batteryLow: BatteryLow,
  batteryMedium: BatteryMedium,
  signal0: CellularSignal0,
  signal1: CellularSignal1,
  signal2: CellularSignal2,
  signal3: CellularSignal3,
  globe: Globe,
  pin: MapPin,
  roadSign: RoadSign,
  directions: Directions,
  tools: Tools,
  toolCase: ToolCase,
  brush: Brush,
  qr: QrCode,
  barcode: Barcode,
  thumbnails: GalleryThumbnails,
  swatch: ColorsSwatch,
  scan: AiScan,
} as const;

export interface PixelIconProps extends React.SVGProps<SVGSVGElement> {
  name: PixelIconName;
  /** pixel size in px (default 20) */
  size?: number;
  /** filled color; defaults to currentColor */
  color?: string;
  title?: string;
}

export const PixelIcon: React.FC<PixelIconProps> = ({
  name,
  size = 20,
  color,
  title,
  className,
  ...props
}) => {
  const Icon = PIXEL_ICONS[name];
  if (!Icon) {
    if (import.meta.env?.DEV) {
      console.warn(`[PixelIcon] unknown icon name: "${name}"`);
    }
    return null;
  }
  return (
    <Icon
      width={size}
      height={size}
      color={color}
      className={className}
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
      {...props}
    />
  );
};

PixelIcon.displayName = 'PixelIcon';

export { PIXEL_ICONS };
